env:
  es2021: true
extends: standard-with-typescript
ignorePatterns: [".eslintrc"]
parserOptions:
  ecmaVersion: latest
  sourceType: module
overrides:
  - files: ["*.spec.ts"]
    env:
      jest: true
    rules: {}
rules: {
  no-use-before-define: "off",
  import/no-named-as-default: "off",
  import/no-named-as-default-member: "off",
  max-len: [
      "warn",
      {
          "code": 120,
          "ignorePattern": "^import",
          "ignoreComments": true
      }
  ],
  no-console: "off",
  no-shadow: "off",
  no-template-curly-in-string: "error",
  accessor-pairs: "error",
  camelcase: "error",
  curly: "error",
  eqeqeq: [
      "error",
      "always"
  ],
  no-alert: "error",
  no-nested-ternary: "error",
  no-return-assign: "error",
  no-unneeded-ternary: "error",
  no-unused-expressions: "error",
  no-useless-concat: "error",
  no-useless-return: "error",
  no-var: "error",
  prefer-const: "error",
  prefer-template: "error",
  radix: "error",
  strict: [
      "error",
      "global"
  ],
  arrow-parens: "error",
  eol-last: "error",
  lines-between-class-members: [
      "error",
      "always",
      {
          "exceptAfterSingleLine": true
      }
  ],
  no-multi-spaces: "error",
  no-multiple-empty-lines: "error",
  no-trailing-spaces: "error",
  quotes: [
      "error",
      "single"
  ],
  semi: "error",
  semi-style: "error",
  space-infix-ops: "error",
}
